# Project: Team37 ClusterCloud2
# Repository: https://github.com/ssaraswati/ClusterCloud2
# City: Melbourne
# Team Members:
#     - jchee@student.unimelb.edu.au, Jone Chee, 634350
#     - phamtq@student.unimelb.edu.au, Tuyen Quang Pham, 381450
#     - eha1@student.unimelb.edu.au,  Emily Ha, 747184
#     - s.saraswati@student.unimelb.edu.au, Shyam Saraswati, 717418
#     - h.yeh1@student.unimelb.edu.au, Hao Yu Yeh, 782692

- hosts: all
  roles:
     - { role: angstwad.docker_ubuntu, sudo: yes }
