# Project: Team37 ClusterCloud2
# Repository: https://github.com/ssaraswati/ClusterCloud2
# City: Melbourne
# Team Members:
#     - jchee@student.unimelb.edu.au, Jone Chee, 634350
#     - phamtq@student.unimelb.edu.au, Tuyen Quang Pham, 381450
#     - eha1@student.unimelb.edu.au,  Emily Ha, 747184
#     - s.saraswati@student.unimelb.edu.au, Shyam Saraswati, 717418
#     - h.yeh1@student.unimelb.edu.au, Hao Yu Yeh, 782692

---
- name: Build an image with the command module
  hosts: searcher
  roles:
     - { role: angstwad.docker_ubuntu, sudo: yes }
  tasks:
    - name: upload the site directory to the docker host
      synchronize: src=../tweetscrape dest=/tmp

    - name: build the image
      command: docker build -t forwardsearch:ex1 /tmp/tweetscrape
      become: true
      
    - name: Create a forward search container
      docker_container:
        name: forwardsearch
        image: forwardsearch:ex1
      become: true

    - name: build the image
      command: docker build -t backsearch:ex1 /tmp/tweetscrape
      become: true
      
    - name: Create a backward search container
      docker_container:
        name: backsearch
        image: backsearch:ex1
        env: 
            SEARCH_FORWARD=False
      become: true

